FROM --platform=linux/amd64 archlinux:latest

RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm firejail bubblewrap bat file fd fzf ripgrep chafa

COPY hyprde/configs/hypr/scripts /root/.config/hypr/scripts
RUN chmod +x /root/.config/hypr/scripts/*.sh

WORKDIR /root
CMD ["bash"]
