import unittest
from unittest.mock import patch
import sys
import os
import tempfile
import tomllib

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

import build_config
import lua_generator


class TestLuaGeneratorBasic(unittest.TestCase):
    """Tests for the Lua generator core."""

    def test_header_generated(self):
        """Test that output starts with the generated header."""
        lua = lua_generator.generate_user_lua({})
        self.assertIn("Generated by hyprde", lua)
        self.assertIn("hyprde.toml", lua)

    def test_programs_as_local_vars(self):
        """Test programs section produces local variables."""
        data = {"programs": {"terminal": "kitty", "fileManager": "thunar"}}
        lua = lua_generator.generate_user_lua(data)
        self.assertIn('local terminal = "kitty"', lua)
        self.assertIn('local fileManager = "thunar"', lua)

    def test_main_mod_from_binds(self):
        """Test mainMod is written from binds section."""
        data = {"binds": {"mainMod": "ALT", "normal": {"list": []}}}
        lua = lua_generator.generate_user_lua(data)
        self.assertIn('local mainMod = "ALT"', lua)

    def test_monitors_hl_monitor_call(self):
        """Test monitors produce hl.monitor() calls."""
        data = {
            "monitors": {
                "rules": ["DP-1, 1920x1080@60, 0x0, 1", ", highres, auto, 1"]
            }
        }
        lua = lua_generator.generate_user_lua(data)
        self.assertIn('hl.monitor({ output = "DP-1", mode = "1920x1080@60", position = "0x0", scale = "1" })', lua)
        self.assertIn('hl.monitor({ output = "", mode = "highres", position = "auto", scale = "1" })', lua)

    def test_env_section(self):
        """Test env section generates hl.config({ env = ... })."""
        data = {"env": {"vars": ["XCURSOR_SIZE,24", "HYPRCURSOR_SIZE,24"]}}
        lua = lua_generator.generate_user_lua(data)
        self.assertIn('hl.config({\n    env = {', lua)
        self.assertIn('"XCURSOR_SIZE,24"', lua)
        self.assertIn('"HYPRCURSOR_SIZE,24"', lua)

    def test_empty_data_does_not_crash(self):
        """Test that empty TOML data produces valid output."""
        lua = lua_generator.generate_user_lua({})
        self.assertIsInstance(lua, str)
        self.assertGreater(len(lua), 0)


class TestLuaGeneratorConfig(unittest.TestCase):
    """Tests for hl.config() output from various sections."""

    def test_general_section(self):
        """Test general section maps col_ keys correctly."""
        data = {"general": {"gaps_in": 5, "col_active_border": "0xff0000"}}
        lua = lua_generator.generate_user_lua(data)
        self.assertIn("gaps_in = 5", lua)
        # col_ prefix should be stripped in Lua output
        self.assertIn('active_border = "0xff0000"', lua)
        self.assertIn("col = {", lua)
        self.assertNotIn("col_active_border", lua)

    def test_input_section(self):
        """Test input section with nested touchpad."""
        data = {
            "input": {
                "kb_layout": "us",
                "follow_mouse": 1,
                "touchpad": {"natural_scroll": False}
            }
        }
        lua = lua_generator.generate_user_lua(data)
        self.assertIn('kb_layout = "us"', lua)
        self.assertIn("follow_mouse = 1", lua)
        self.assertIn("natural_scroll = false", lua)

    def test_decoration_blur(self):
        """Test decoration with nested blur."""
        data = {"decoration": {"rounding": 10, "blur": {"enabled": True, "size": 3}}}
        lua = lua_generator.generate_user_lua(data)
        self.assertIn("rounding = 10", lua)
        self.assertIn("blur = {", lua)
        self.assertIn("enabled = true", lua)
        self.assertIn("size = 3", lua)
        # Internal keys should be skipped
        self.assertNotIn("waybar_opacity", lua)

    def test_animations(self):
        """Test animations produce hl.curve() and hl.animation() calls."""
        data = {"animations": {"enabled": True, "bezier": "myB, 0.05, 0.9, 0.1, 1.05"}}
        lua = lua_generator.generate_user_lua(data)
        self.assertIn("enabled = true", lua)
        self.assertIn('hl.curve("myB", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })', lua)

    def test_misc_section(self):
        """Test misc section booleans render correctly."""
        data = {"misc": {"disable_hyprland_logo": True, "force_default_wallpaper": 0}}
        lua = lua_generator.generate_user_lua(data)
        self.assertIn("disable_hyprland_logo = true", lua)
        self.assertIn("force_default_wallpaper = 0", lua)


class TestLuaGeneratorBinds(unittest.TestCase):
    """Tests for keybind parsing and generation."""

    def test_simple_bind(self):
        """Test a simple killactive bind."""
        data = {"binds": {"normal": {"list": ["$mainMod, Q, killactive,"]}}, "binds": {"mainMod": "SUPER"}}
        # Rebuild properly
        data = {"binds": {"mainMod": "SUPER", "normal": {"list": ["$mainMod, Q, killactive,"]}}}
        lua = lua_generator.generate_user_lua(data)
        self.assertIn('hl.bind("SUPER + Q", hl.dsp.window.close())', lua)

    def test_exec_bind_resolves_vars(self):
        """Test exec bind resolves $terminal and $mainMod."""
        data = {
            "programs": {"terminal": "ghostty"},
            "binds": {"mainMod": "SUPER", "normal": {"list": ["$mainMod, T, exec, $terminal"]}}
        }
        lua = lua_generator.generate_user_lua(data)
        self.assertIn('hl.bind("SUPER + T", hl.dsp.exec_cmd("ghostty"))', lua)

    def test_release_bind(self):
        """Test release bind flag."""
        data = {"binds": {"mainMod": "SUPER", "release": {"list": ["$mainMod, space, exec, spotlight"]}}}
        lua = lua_generator.generate_user_lua(data)
        self.assertIn(", { release = true }", lua)

    def test_repeat_bind(self):
        """Test repeat bind flag."""
        data = {"binds": {"mainMod": "SUPER", "repeat": {"list": ["$mainMod SHIFT, up, resizeactive, 0 -10"]}}}
        lua = lua_generator.generate_user_lua(data)
        self.assertIn(", { repeating = true }", lua)

    def test_mouse_bind(self):
        """Test mouse bind."""
        data = {"binds": {"mainMod": "SUPER", "mouse": {"list": ["$mainMod, mouse:272, movewindow"]}}}
        lua = lua_generator.generate_user_lua(data)
        self.assertIn(", nil)", lua)

    @patch("lua_generator._check_hyprexpo", return_value=True)
    def test_custom_dispatcher(self, mock_check_hyprexpo):
        """Test plugin dispatchers fall back to hl.dispatch()."""
        data = {
            "plugins": {"enabled": ["hyprexpo"]},
            "binds": {"mainMod": "SUPER", "normal": {"list": ["$mainMod, G, hyprexpo:expo, toggle"]}}
        }
        lua = lua_generator.generate_user_lua(data)
        self.assertIn('hl.dispatch("hyprexpo:expo", "toggle")', lua)

    def test_empty_mod_bind(self):
        """Test bind with empty modifier (leading comma)."""
        data = {"binds": {"mainMod": "SUPER", "normal": {"list": [", escape, submap, reset"]}}}
        lua = lua_generator.generate_user_lua(data)
        self.assertIn('hl.bind("escape", hl.dsp.submap("reset"))', lua)

    def test_bind_expands_home(self):
        """Test $HOME is expanded in exec args."""
        data = {"binds": {"mainMod": "SUPER", "normal": {"list": [", Print, exec, $HOME/script.sh"]}}}
        lua = lua_generator.generate_user_lua(data)
        home = os.path.expanduser("~")
        self.assertIn(f'hl.dsp.exec_cmd("{home}/script.sh")', lua)


class TestLuaGeneratorWindowRules(unittest.TestCase):
    """Tests for window rule conversion."""

    def test_float_rule(self):
        """Test float rule produces hl.windowrule with float=true."""
        data = {"rules": {"window": ["float, class:^(MyApp)$"]}}
        lua = lua_generator.generate_user_lua(data)
        self.assertIn('hl.window_rule({ match = { class = "^(MyApp)$" } }, { float = true })', lua)

    def test_pin_title_rule(self):
        """Test pin rule with title selector."""
        data = {"rules": {"window": ["pin, title:^(PinnedApp)$"]}}
        lua = lua_generator.generate_user_lua(data)
        self.assertIn('hl.window_rule({ match = { title = "^(PinnedApp)$" } }, { pin = true })', lua)

    def test_suppressevent_rule(self):
        """Test suppressevent rule."""
        data = {"rules": {"window": ["suppressevent maximize, class:.*"]}}
        lua = lua_generator.generate_user_lua(data)
        self.assertIn('suppress_event = "maximize"', lua)

    def test_size_rule(self):
        """Test size rule."""
        data = {"rules": {"window": ["size 80% 85%, class:(fzf)"]}}
        lua = lua_generator.generate_user_lua(data)
        self.assertIn('size = "80% 85%"', lua)


class TestLuaGeneratorCustom(unittest.TestCase):
    """Tests for [custom] section handling."""

    def test_lua_lines_emitted_verbatim(self):
        """Test lua_lines are emitted verbatim."""
        data = {"custom": {"lua_lines": ['hl.config({ misc = { disable_logo = false } })']}}
        lua = lua_generator.generate_user_lua(data)
        self.assertIn("hl.config({ misc = { disable_logo = false } })", lua)

    def test_hyprlang_lines_warned_and_skipped(self):
        """Test hyprlang lines are commented out in Lua mode."""
        data = {"custom": {"lines": ["bind = SUPER, Q, exec, kitty"]}}
        lua = lua_generator.generate_user_lua(data)
        self.assertIn("IGNORED", lua)
        self.assertNotIn('hl.bind("SUPER, Q"', lua)

    def test_empty_custom_skipped(self):
        """Test empty custom section is harmless."""
        lua = lua_generator.generate_user_lua({"custom": {}})
        self.assertIsInstance(lua, str)


class TestLuaGeneratorAutostart(unittest.TestCase):
    """Tests for autostart generation."""

    def test_exec_once_becomes_hl_on(self):
        """Test exec_once items become hl.on handlers using exec_cmd."""
        data = {"autostart": {"exec_once": ["waybar", "mako"]}}
        lua = lua_generator.generate_user_lua(data)
        self.assertIn('hl.on("hyprland.start", function() hl.dsp.exec_cmd("waybar") end)', lua)
        self.assertIn('hl.on("hyprland.start", function() hl.dsp.exec_cmd("mako") end)', lua)

    def test_autostart_resolves_program_vars(self):
        """Test $notification_service is resolved in autostart."""
        data = {
            "programs": {"notification_service": "mako", "status_bar": "waybar"},
            "autostart": {"exec_once": ["$notification_service & $status_bar"]}
        }
        lua = lua_generator.generate_user_lua(data)
        self.assertIn('hl.dsp.exec_cmd("mako & waybar")', lua)


class TestBuildConfigAtomicWrite(unittest.TestCase):
    """Tests for atomic file write operations."""

    def test_atomic_write_success(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            test_file = os.path.join(tmpdir, "test.txt")
            build_config.atomic_write(test_file, "test content")
            with open(test_file, 'r') as f:
                self.assertEqual(f.read(), "test content")

    def test_atomic_write_failure_cleanup(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            test_file = os.path.join(tmpdir, "test.txt")
            os.chmod(tmpdir, 0o555)
            try:
                build_config.atomic_write(test_file, "content")
            except OSError:
                pass
            os.chmod(tmpdir, 0o755)
            temp_pattern = f"{test_file}.tmp."
            temp_files = [f for f in os.listdir(tmpdir) if f.startswith(os.path.basename(temp_pattern))]
            self.assertEqual(len(temp_files), 0)


class TestBuildConfigSecurity(unittest.TestCase):
    """Tests for security validation."""

    def test_validate_shell_safe_valid(self):
        result = build_config.validate_shell_safe("/home/user/path", "test.field")
        self.assertEqual(result, "/home/user/path")

    def test_validate_shell_safe_invalid_semicolon(self):
        with self.assertRaises(ValueError):
            build_config.validate_shell_safe("path; rm -rf /", "test.field")

    def test_validate_shell_safe_invalid_pipe(self):
        with self.assertRaises(ValueError):
            build_config.validate_shell_safe("path | cat", "test.field")


class TestBuildConfigHypridle(unittest.TestCase):
    """Tests for hypridle config generation."""

    def setUp(self):
        self.patcher = patch('build_config.atomic_write')
        self.mock_atomic_write = self.patcher.start()

    def tearDown(self):
        self.patcher.stop()

    def test_hypridle_basic(self):
        """Test basic hypridle config generation."""
        mock_data = {
            "idle": {
                "lock_timeout": 300,
                "screen_off_timeout": 330,
                "suspend_timeout": 1800
            }
        }

        build_config.generate_hypridle_conf(mock_data)

        written = ""
        for call in self.mock_atomic_write.call_args_list:
            if call.args[0] == build_config.HYPRIDLE_CONF:
                written = call.args[1]
                break

        self.assertIn("timeout = 300", written)
        self.assertIn("timeout = 330", written)
        self.assertIn("timeout = 1800", written)
        self.assertIn("lock_cmd = pidof hyprlock || hyprlock", written)

    def test_hypridle_dpms_syntax(self):
        """Test dpms commands use hl.dsp.dpms syntax."""
        mock_data = {"idle": {"lock_timeout": 300, "screen_off_timeout": 330, "suspend_timeout": 1800}}

        build_config.generate_hypridle_conf(mock_data)

        written = ""
        for call in self.mock_atomic_write.call_args_list:
            if call.args[0] == build_config.HYPRIDLE_CONF:
                written = call.args[1]
                break

        self.assertIn("hl.dsp.dpms(\"on\")", written)
        self.assertIn("hl.dsp.dpms(\"off\")", written)
        # Old syntax should NOT appear
        self.assertNotIn("hyprctl dispatch dpms", written)

    def test_hypridle_no_idle_section(self):
        """Test that hypridle generation is skipped without idle section."""
        mock_data = {}

        with patch("builtins.open") as mocked_file:
            build_config.generate_hypridle_conf(mock_data)
            mocked_file.assert_not_called()


class TestBuildConfigWallpaperSchedule(unittest.TestCase):
    """Tests for wallpaper schedule generation."""

    def test_three_slot_schedule(self):
        mock_data = {
            "wallpapers": {
                "mode": "dynamic",
                "interval": 300,
                "schedule": {
                    "morning_start": "6:00 AM",
                    "noon_start": "12:00 PM",
                    "evening_start": "6:00 PM"
                },
                "directories": {
                    "morning": "sunrise",
                    "noon": "daylight",
                    "evening": "sunset"
                }
            }
        }

        with patch("build_config.atomic_write") as mock_write:
            build_config.generate_wallpaper_schedule_config(mock_data)

            mock_write.assert_called_once()
            content = mock_write.call_args[0][1]

            self.assertIn('WALLPAPER_MORNING_START="06:00"', content)
            self.assertIn('WALLPAPER_NOON_START="12:00"', content)
            self.assertIn('WALLPAPER_EVENING_START="18:00"', content)
            self.assertIn('WALLPAPER_MORNING_DIR="sunrise"', content)
            self.assertIn('WALLPAPER_NOON_DIR="daylight"', content)
            self.assertIn('WALLPAPER_EVENING_DIR="sunset"', content)
            self.assertNotIn("NIGHT_START", content)

    def test_schedule_default_values(self):
        mock_data = {"wallpapers": {"mode": "dynamic", "schedule": {}, "directories": {}}}

        with patch("build_config.atomic_write") as mock_write:
            build_config.generate_wallpaper_schedule_config(mock_data)

            mock_write.assert_called_once()
            content = mock_write.call_args[0][1]
            self.assertIn('WALLPAPER_MORNING_START="06:00"', content)
            self.assertIn('WALLPAPER_MORNING_DIR="morning"', content)

    def test_schedule_no_wallpapers_section(self):
        mock_data = {}
        with patch("build_config.atomic_write") as mock_write:
            build_config.generate_wallpaper_schedule_config(mock_data)
            mock_write.assert_not_called()


class TestBuildConfigTimeConversion(unittest.TestCase):
    """Tests for time format conversion."""

    def test_12h_to_24h(self):
        self.assertEqual(build_config.convert_12h_to_24h("6:00 AM"), "06:00")
        self.assertEqual(build_config.convert_12h_to_24h("12:00 PM"), "12:00")
        self.assertEqual(build_config.convert_12h_to_24h("6:00 PM"), "18:00")
        self.assertEqual(build_config.convert_12h_to_24h("12:00 AM"), "00:00")

    def test_invalid_time_format(self):
        with self.assertRaises(ValueError):
            build_config.convert_12h_to_24h("invalid")
        with self.assertRaises(ValueError):
            build_config.convert_12h_to_24h("25:00 AM")


class TestLuaGeneratorValueHelpers(unittest.TestCase):
    """Tests for low-level value formatting helpers."""

    def test_value_to_lua_bool(self):
        self.assertEqual(lua_generator._value_to_lua(True), "true")
        self.assertEqual(lua_generator._value_to_lua(False), "false")

    def test_value_to_lua_int(self):
        self.assertEqual(lua_generator._value_to_lua(42), "42")

    def test_value_to_lua_float(self):
        self.assertEqual(lua_generator._value_to_lua(3.14), "3.14")

    def test_value_to_lua_str(self):
        self.assertEqual(lua_generator._value_to_lua("hello"), '"hello"')

    def test_value_to_lua_escaped_str(self):
        self.assertEqual(lua_generator._value_to_lua('say "hi"'), '"say \\"hi\\""')

    def test_value_to_lua_list(self):
        result = lua_generator._value_to_lua(["a", "b"])
        self.assertEqual(result, '{ "a", "b" }')

    def test_dict_to_lua_table(self):
        result = lua_generator._dict_to_lua_table({"a": 1, "b": "two"}, 0)
        self.assertIn("a = 1", result)
        self.assertIn('b = "two"', result)
        self.assertTrue(result.startswith("{"))


class TestBuildConfigEndToEnd(unittest.TestCase):
    """End-to-end test: run generate_and_write_lua with real TOML data."""

    def test_generate_and_write_lua_creates_file(self):
        """Test that generate_and_write_lua writes a valid Lua file."""
        data = {
            "programs": {"terminal": "kitty"},
            "binds": {"mainMod": "SUPER", "normal": {"list": ["$mainMod, Q, killactive,"]}}
        }

        with tempfile.TemporaryDirectory() as tmpdir:
            lua_path = os.path.join(tmpdir, "hyprland.lua")
            with patch("build_config.LUA_CONF", lua_path):
                build_config.generate_and_write_lua(data)
                self.assertTrue(os.path.exists(lua_path))
                with open(lua_path) as f:
                    content = f.read()
                self.assertIn("Generated by hyprde", content)
                self.assertIn("kitty", content)
                self.assertIn("hl.bind", content)


class TestBuildConfigExpandUserPath(unittest.TestCase):
    """Tests for path expansion."""

    def test_expand_dollar_home(self):
        expanded = build_config.expand_user_path("$HOME/.config")
        self.assertEqual(expanded, os.path.expanduser("~/.config"))

    def test_expand_tilde(self):
        expanded = build_config.expand_user_path("~/.config")
        self.assertEqual(expanded, os.path.expanduser("~/.config"))

    def test_empty_path(self):
        self.assertEqual(build_config.expand_user_path(""), "")


class TestBuildConfigValidation(unittest.TestCase):
    """Tests for config validation."""

    def test_valid_config_no_warnings(self):
        warnings = build_config.validate_config({"programs": {"terminal": "kitty"}})
        self.assertIsInstance(warnings, list)

    def test_unknown_section_warning(self):
        warnings = build_config.validate_config({"typo_section": {}})
        self.assertTrue(any("Unknown section" in w for w in warnings))

    def test_deprecated_custom_lines(self):
        warnings = build_config.validate_config({"custom": {"lines": ["bind = ..."]}})
        self.assertTrue(any("deprecated" in w for w in warnings))

    def test_bad_main_mod_warning(self):
        warnings = build_config.validate_config({"binds": {"mainMod": "super"}})
        self.assertTrue(any("uppercase" in w for w in warnings))


class TestLuaGeneratorShorthandBinds(unittest.TestCase):
    """Tests for shorthand binds (dict format)."""

    def test_shortcut_conversion(self):
        """Test shorthand bind produces correct Lua."""
        data = {
            "binds": {
                "mainMod": "SUPER",
                "normal": {
                    "shortcuts": {
                        "SUPER, T": "exec, kitty",
                        "SUPER, Q": "killactive",
                    }
                }
            }
        }
        lua = lua_generator.generate_user_lua(data)
        self.assertIn('hl.bind("SUPER + T", hl.dsp.exec_cmd("kitty"))', lua)
        self.assertIn('hl.bind("SUPER + Q", hl.dsp.window.close())', lua)

    def test_shortcut_with_release(self):
        """Test shorthand bind with release flag."""
        data = {
            "binds": {
                "mainMod": "SUPER",
                "release": {
                    "shortcuts": {
                        "SUPER, space": "exec, spotlight",
                    }
                }
            }
        }
        lua = lua_generator.generate_user_lua(data)
        self.assertIn(", { release = true }", lua)

    def test_shorthand_and_list_together(self):
        """Test both list and shortcuts in the same section."""
        data = {
            "binds": {
                "mainMod": "SUPER",
                "normal": {
                    "list": ["$mainMod, Q, killactive,"],
                    "shortcuts": {"SUPER, T": "exec, kitty"},
                }
            }
        }
        lua = lua_generator.generate_user_lua(data)
        self.assertIn('hl.bind("SUPER + T", hl.dsp.exec_cmd("kitty"))', lua)
        self.assertIn('hl.bind("SUPER + Q", hl.dsp.window.close())', lua)


class TestBuildConfigInjectDefaults(unittest.TestCase):
    """Tests for default injection."""

    @patch("build_config.auto_detect_monitors", return_value=["eDP-1, 1920x1080@60, 0x0, 1"])
    def test_monitors_auto_detected_when_missing(self, mock_detect):
        result = build_config.inject_defaults({})
        self.assertIn("monitors", result)
        self.assertEqual(result["monitors"]["rules"], ["eDP-1, 1920x1080@60, 0x0, 1"])

    @patch("build_config.auto_detect_monitors", return_value=[])
    def test_no_monitors_when_detect_fails(self, mock_detect):
        result = build_config.inject_defaults({})
        self.assertNotIn("monitors", result)

    def test_binds_defaults_inserted(self):
        result = build_config.inject_defaults({})
        self.assertIn("binds", result)
        self.assertEqual(result["binds"]["mainMod"], "SUPER")



class TestGeneratedLuaEndToEnd(unittest.TestCase):
    """End-to-end verification of generated Lua from the actual TOML."""

    def setUp(self):
        toml_path = os.path.join(os.path.dirname(__file__), "..", "hyprde.toml")
        with open(toml_path, "rb") as f:
            self.data = tomllib.load(f)
        self.data.setdefault("binds", {}).setdefault("mainMod", "SUPER")

    @patch("lua_generator._is_plugin_installed", return_value=False)
    def test_generated_lua_has_all_sections(self, mock_plugin):
        lua = lua_generator.generate_user_lua(self.data)

        self.assertIn("Generated by hyprde", lua)
        self.assertIn("hl.monitor({", lua)
        self.assertIn("hl.config({", lua)
        self.assertIn("-- [[ Keybindings ]]", lua)
        self.assertIn("-- [[ Window Rules ]]", lua)
        self.assertIn("-- [[ Animations ]]", lua)

    @patch("lua_generator._is_plugin_installed", return_value=False)
    def test_bind_key_format_uses_plus(self, mock_plugin):
        lua = lua_generator.generate_user_lua(self.data)
        multi_binds = 0
        for line in lua.splitlines():
            if line.startswith('hl.bind("') and not line.startswith('hl.bind("XF86'):
                if line.split('"')[1].count(" ") > 0:
                    self.assertIn(" + ", line, f"Bind missing '+' separator: {line}")
                    multi_binds += 1
        self.assertGreater(multi_binds, 5)

    @patch("lua_generator._is_plugin_installed", return_value=False)
    def test_monitor_uses_table_format(self, mock_plugin):
        lua = lua_generator.generate_user_lua(self.data)
        self.assertRegex(lua, r"hl\.monitor\(\{.*output.*mode.*position.*scale.*\}")

    @patch("lua_generator._is_plugin_installed", return_value=False)
    def test_animation_uses_hl_animation_calls(self, mock_plugin):
        lua = lua_generator.generate_user_lua(self.data)
        self.assertIn("hl.curve(", lua)
        self.assertIn("hl.animation({ leaf =", lua)
        self.assertIn("bezier =", lua)

    @patch("lua_generator._is_plugin_installed", return_value=False)
    def test_border_colors_under_col_subtable(self, mock_plugin):
        lua = lua_generator.generate_user_lua(self.data)
        if "active_border" in lua or "inactive_border" in lua:
            self.assertIn("col = {", lua)

    @patch("lua_generator._is_plugin_installed", return_value=False)
    def test_window_rules_use_match_wrapper(self, mock_plugin):
        lua = lua_generator.generate_user_lua(self.data)
        for line in lua.splitlines():
            if line.strip().startswith("hl.window_rule("):
                self.assertIn("match = {", line, f"Rule missing match wrapper: {line}")

    @patch("lua_generator._is_plugin_installed", return_value=False)
    def test_no_pseudotile_in_output(self, mock_plugin):
        lua = lua_generator.generate_user_lua(self.data)
        self.assertNotIn("pseudotile", lua)

    @patch("lua_generator._is_plugin_installed", return_value=False)
    def test_togglesplit_has_default_arg(self, mock_plugin):
        lua = lua_generator.generate_user_lua(self.data)
        self.assertIn('hl.dsp.layout("togglesplit")', lua)

    @patch("lua_generator._is_plugin_installed", return_value=False)
    def test_fullscreen_uses_window_fullscreen(self, mock_plugin):
        lua = lua_generator.generate_user_lua(self.data)
        self.assertIn("hl.dsp.window.fullscreen({", lua)

    @patch("lua_generator._is_plugin_installed", return_value=False)
    def test_togglefloating_uses_action_toggle(self, mock_plugin):
        lua = lua_generator.generate_user_lua(self.data)
        self.assertIn('hl.dsp.window.float({ action = "toggle" })', lua)


if __name__ == '__main__':
    unittest.main(verbosity=2)
